language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"
jobs:
    include:
        - python: "3.8"
          install:
              - pip install flake8 black
          script:
              - flake8 aioreloader/ setup.py
              - black --check aioreloader/ setup.py

cache: pip

install:
    - pip install flake8

script:
    - flake8 aioreloader/ setup.py

deploy:
    provider: pypi
    user: and800
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        python: "3.8"
